FROM jenkins/jenkins:lts

USER root

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv && \
    apt-get clean

# Add python path for all users including jenkins
ENV PATH="/usr/bin:$PATH"

USER jenkins
